default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: language-school_development

test:
  <<: *default
  database: language-school_test

production:
  <<: *default
  database: language-school_production
  username: language-school
  password: 123
